DELETE FROM LoanReminders;
DELETE FROM Loans;
DELETE FROM Customers;
COMMIT;
INSERT INTO Customers VALUES (1, 'Rachel', 65, 12000, 8.5, 'FALSE');
INSERT INTO Customers VALUES (2, 'Shinchan', 45, 9500, 9.2, 'FALSE');
INSERT INTO Customers VALUES (3, 'Harry', 70, 15000, 7.8, 'FALSE');

COMMIT;

INSERT INTO Loans VALUES (201, 1, SYSDATE + 10); 
INSERT INTO Loans VALUES (202, 2, SYSDATE + 40); 
INSERT INTO Loans VALUES (203, 3, SYSDATE + 5);

COMMIT;